# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Task. Who wants to be a millionaire?' do
  # Comment the next line if you don't want to use dynamic frameworks

pod 'lottie-ios'


  # Pods for Task. Who wants to be a millionaire?

end
