# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Task 26. Get запросы' do
  # Comment the next line if you don't want to use dynamic frameworks
pod 'lottie-ios'

  # Pods for Task 26. Get запросы

end
